# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0004_auto_20170221_0000'),
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.CrontabSchedule'),
        ),
    ]
