# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0004_auto_20170221_0000'),
        ('mood', '0002_profile_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.PeriodicTask'),
        ),
    ]
