# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0003_profile_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodresponse',
            name='tone',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
