# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0004_moodpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodpoint',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
