# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0005_moodresponse_related_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodresponse',
            name='tone',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
